INSERT INTO artists (name) VALUES
  ('Yo Maps'),
  ('Chef 187'),
  ('Slapdee'),
  ('Cleo Ice Queen'),
  ('Macky 2'),
  ('Pompi'),
  ('Bobby East'),
  ('Jemax'),
  ('Chanda na Kay'),
  ('Y Celeb'),
  ('Blood Kid'),
  ('B Quan'),
  ('Shokki'),
  ('Bow Chase'),
  ('Drimz'),
  ('Izrael'),
  ('Muzo AKA Alphonso'),
  ('Willz Mr Nyopole'),
  ('Tiye P'),
  ('Petersen Zagaze'),
  ('KB'),
  ('Slap Dee'),
  ('Stevo'),
  ('Exile'),
  ('Pilato'),
  ('Wezi'),
  ('Mampi'),
  ('Judy Yo'),
  ('Esther Chungu'),
  ('Ephraim'),
  ('Afunika'),
  ('JK'),
  ('Ozzy'),
  ('Kaladoshas'),
  ('Nez Long'),
  ('Daev'),
  ('T-Sean'),
  ('Cactus Agony'),
  ('Vinchenzo'),
  ('Shenky'),
  ('Kekero'),
  ('Xaven'),
  ('Natasha Chansa'),
  ('Towela Kaira'),
  ('Ludo'),
  ('Chuzhe Int'),
  ('Kopala Swag'),
  ('Jae Cash'),
  ('Camstar'),
  ('Driemo'),
  ('Dope G'),
  ('Sulu'),
  ('Mic Burner'),
  ('Koby'),
  ('Kunta Kinte'),
  ('Slap D'),
  ('Coziem'),
  ('Chali 2na'),
  ('Frankie Kumwenda'),
  ('Smooth'),
  ('Dalisoul'),
  ('Ruff Kid'),
  ('Chill Homie'),
  ('Dope Boys'),
  ('Shenky Shekinah'),
  ('Roberto'),
  ('Lota'),
  ('Mwenye')
ON CONFLICT DO NOTHING;